# Generated by Django 6.0.1 on 2026-01-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True)),
                ('perfilactivo', models.IntegerField(default=1)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/foto/')),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='perfil/cv/')),
            ],
            options={
                'verbose_name': 'Datos personales',
                'verbose_name_plural': 'Datos personales',
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('descripcioncurso', models.CharField(blank=True, max_length=100, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='cursos/certificados/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencilaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('lugarempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('emailempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField(blank=True, null=True)),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='experiencia/certificados/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificador', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fechareconocimiento', models.DateField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='reconocimientos/evidencias/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valordelbien', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='cv.datospersonales')),
            ],
        ),
    ]
