# Generated by Django 5.0.10 on 2026-01-23 08:38

import cv.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_fecha_futura]),
        ),
        migrations.CreateModel(
            name='ConfiguracionVisibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_datos_personales', models.BooleanField(default=True, verbose_name='Mostrar Datos Personales')),
                ('mostrar_experiencia_laboral', models.BooleanField(default=True, verbose_name='Mostrar Experiencia Laboral')),
                ('mostrar_cursos', models.BooleanField(default=True, verbose_name='Mostrar Cursos Realizados')),
                ('mostrar_reconocimientos', models.BooleanField(default=True, verbose_name='Mostrar Reconocimientos')),
                ('mostrar_productos_academicos', models.BooleanField(default=True, verbose_name='Mostrar Productos Académicos')),
                ('mostrar_productos_laborales', models.BooleanField(default=True, verbose_name='Mostrar Productos Laborales')),
                ('mostrar_venta_garage', models.BooleanField(default=False, verbose_name='Mostrar Venta Garage')),
                ('mostrar_foto_perfil', models.BooleanField(default=True, verbose_name='Mostrar Foto de Perfil')),
                ('mostrar_contacto', models.BooleanField(default=True, verbose_name='Mostrar Información de Contacto')),
                ('mostrar_cv_descargable', models.BooleanField(default=True, verbose_name='Mostrar CV Descargable')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_visibilidad', to='cv.datospersonales', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Configuración de Visibilidad',
                'verbose_name_plural': 'Configuración de Visibilidad',
            },
        ),
    ]
