# Generated by Django 5.0.10 on 2026-01-23 17:41

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_ventagarage_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(blank=True, null=True, validators=[cv.models.validar_horas_no_negativas]),
        ),
    ]
