# Generated by Django 5.0.10 on 2026-01-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_ventagarage_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='garage/productos/'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='garage/productos/'),
        ),
    ]
